### ISSUE TITLE
Product prices not updating via API in WordPress

### ISSUE THREAD

**Issue by cikez** [godaddy/wp-reseller-store#106]
Hello,

Please fix the API syncing back to Reseller WordPress products. They are not updating the prices on the configured interval. The only way to fix is this is to completely delete the product in WordPress and re-import them from the Storefront which is obviously not ideal because doing this changes the product postid.

I put in a ticket to reseller support on August 6, 2020 (Incident ID: 42555204) and received a response on August 14, 2020 stating “We are looking into what changed with WordPress to block the syncing with our servers pricing at this time. I do not have an ETA when we will be pushing a fix out but we will as soon as we have resolved this. But it is something that is currently with the dev team to dig further into.”

2 months and still not fixed, so I am posting this here to get an update and hopefully get some movement on a fix.

Thanks,
Kyle

**Comment by cjl014** [comment]
Please fix this.

**Comment by cberesford-godaddy** [comment]
Hi @cikez - I'm currently going through several older open issues. I see this is from quite a while ago. I believe the automated pricing sync feature was removed some time ago. To update product pricing, you can re-import the product catalog and that will fetch your latest configured prices. I'm going to mark this issue as resolved, but I'd be happy to re-open it if you have any further issues or questions with the plugin. Thanks and have a nice day!
