### ISSUE TITLE
Plugin not activating giving 500 internal error

### ISSUE THREAD

**Issue by ZahidServers** [godaddy/wp-reseller-store#122]
![image](https://user-images.githubusercontent.com/63946803/144753653-29099c24-2e7b-45c6-80ee-0dad6271218d.png)
Getting error while activating plugin with my basic reseller plan I asked GoDaddy support but they had no idea on this issue is it due to I have already launched the site using GoDaddy's default way of reseller here webaon.com my site, if so then how I undo it and do it using WordPress again. Note I have uninstall and install WordPress many times and flushed caches opened in private window all things that GoDaddy support told me to do.

**Comment by cberesford-godaddy** [comment]
Hi @ZahidServers - I'm currently going through several older open issues. I see this is from quite a while ago. This appears to have been an issue with the plugin not being able to talk to the API (likely errors from the API at the time you were trying to set up). I'm going to mark this issue as resolved, but I'd be happy to re-open it if you have any further issues or questions with the plugin. Thanks and have a nice day!
