### ISSUE TITLE
Domain search error

### ISSUE THREAD

**Issue by loudbel** [godaddy/wp-reseller-store#124]
Hello everyone,
Anyone can help with this new issue ?

search domain not working anymore
Error: JSONP request to https://www.secureserver.net/api/v1/domains/******/?pageSize=1&q=domain.com failed

on demo too : https://godaddy.github.io/domain-search/

thanks

**Comment by loudbel** [comment]
it was a godaddy issue, they just resolved the issue

**Comment by wanasms** [comment]
Mine still doesn't work, any idea on how to fix it, there's no update to the plugin either

**Comment by wanasms** [comment]
My domain search works but going to the cart doesn't https://share.cleanshot.com/NbPw0Z7v
