### ISSUE TITLE
Domain search doesn't work, Serious API issues. 

### ISSUE THREAD

**Issue by shred787** [godaddy/wp-reseller-store#144]
The reseller plugin throws error:

" Error: JSONP request to https://www.secureserver.net/api/v1/domains/583571/?pageSize=5&q=domainiwanttobuy failed"

On domain searches.

So something has happened recently that has broken this plugin.

This is a very widely reported problem and I need this to be resolved ASAP. Because there's no point paying for reseller account if the reseller API is not accessible to me.

**Comment by cberesford-godaddy** [comment]
Hi @shred787 - I found a recent update to the Web Application Firewall that supports the www.secureserver.net/api/v1/domains/* endpoint in question that appeared to start erroneously blocking these JSONP requests. This has been rolled back. Can you confirm that your domain searches via the plugin are working again?

**Comment by shred787** [comment]
> Hi @shred787 - I found a recent update to the Web Application Firewall that supports the [www.secureserver.net/api/v1/domains/](http://www.secureserver.net/api/v1/domains/)* endpoint in question that appeared to start erroneously blocking these JSONP requests. This has been rolled back. Can you confirm that your domain searches via the plugin are working again?

I will check this out immediately.

Please bear with me for a few minutes.

I will report back shortly.

**Comment by shred787** [comment]
No problem at all. I really do like the plugin it's just that issues like this are perplexing and of course the plugin is integral to my business plan at the moment so it's important that I keep on top of it. 

Can I ask what the roadmap of this is? Because people on Wordpress forums believe the plugin is dead or abandoned.

**Comment by cberesford-godaddy** [comment]
@shred787 I'm glad to hear that and we are always here to help. I can't sure a roadmap at the moment, but this is something that is flagged with our community team to re-establish communications and updates for. I can confirm that the plugin is not dead and not abandoned - we are beginning to re-vamp development efforts on it since it had been previously unmaintained internally. It is also worth noting that this is an open-source plugin and contributions from the community are certainly welcomed too :)

**Comment by shred787** [comment]
Great stuff. Cheers Chris. I'll get back onto my business plan and see how things get on and report back here if I discover any further issues or have further suggestions. Thanks again!

**Comment by cberesford-godaddy** [comment]
Best of luck to you!
