### ISSUE TITLE
Plugin Conflicts

### ISSUE THREAD

**Issue by brelandr** [godaddy/wp-reseller-store#39]
I have found 3 plugins that appear to be conflicting with the activation

on a 2016 wordpress them

only 3 plugins active other than the Godaddy reseller 

Widget Context Version 1.0.5
WP Edit Pro Version 4.4.2
Soliloquy Version 2.5.3.1 

will not activate with these install..  (any of the 3).. if I deactivate all 3 plugins it will install

**Comment by bfocht** [comment]
@brelandr thanks.   I will take a look.  my guess is that they are some how conflicting with creating the `custom post type`

**Comment by brelandr** [comment]
Thank you
