### ISSUE TITLE
Shortcode renders code in wrong place

### ISSUE THREAD

**Issue by toman** [godaddy/wp-reseller-store#48]
Creating a page and placing the rstore_product shortcode within a div results in the product markup being written outside of and before the div. I don't usually write in PHP but I think the problem is line 147 in includes/widgets/class-product.php . The  echo should be a return as echo will write immediately to the browser. The other shortcodes seem to have similar issues. 
Reading up on widgets it looks like this is a difference between widgets and shortcodes. Widgets want the result to be echoed, shortcodes want the result returned.  I would suggest refactoring the guts of the widget() function into a separate render() function and then echo the result of that in widget() and return the result in shortcode() so that code doesn't have to be duplicated.

**Comment by bfocht** [comment]
Thanks for the details.  I have added these details to our internal issue tracking system.  I will post an update here after doing some testing and coming up with a solution.
