### ISSUE TITLE
login widget doesn't display logged in user

### ISSUE THREAD

**Issue by ynunez** [godaddy/wp-reseller-store#61]
After login the login widget doesn't display the logged in user. The request to `https://gui.secureserver.net/pcjson/standardheaderfooter/` does not return the user info (first and last name)

**Comment by bfocht** [comment]
Please contact our support team.  They can help verify that the custom domain is setup properly in the Reseller Control Center.  The custom domain must be setup correctly so that a cookie can be properly written to the domain that your WordPress site is running on.
