### ISSUE TITLE
Domain search shortcode not adding domains to cart

### ISSUE THREAD

**Issue by padred123** [godaddy/wp-reseller-store#62]
The domain search shortcode is not adding domains to the cart. 
I am using my own theme and had to do some customizations to the plugin to make it look the way I wanted.
Maybe I need to attach a JS file..?

[Example of issue](https://puu.sh/zdi0E/95a617a80e.mp4)

**Comment by bfocht** [comment]
Thank you for providing the video.  I noticed in the video that the `Continue to cart` button is not being displayed in the domain widget. Are you hiding this button, or is there a defect that is causing this button to not display?  The way that the domain search feature works, is that clicking the `Continue to cart` button within the search widget is what triggers the domain(s) to be added to cart.  

For now this button is the current design, and we appreciate your feedback on it and will evaluate how we can improve the plugin.

**Comment by padred123** [comment]
Yes that was my issue.  I hid the "add to cart" button. I think that is a dealbreaker for me because it takes away from the "flow" of helping my clients easily choose and purchase products that I recommend.  I would prefer to allow them to add the domains to the cart along with other products and then checkout. 

Thx
