### ISSUE TITLE
login shortcode not displaying first/last name of account when logged in.

### ISSUE THREAD

**Issue by P-X-L** [godaddy/wp-reseller-store#63]
Hey guys! great plugin to connect to the reseller account but I've been having issues on placing my cart and login shortcode in my header. I was hoping that one of you can either look at it or fix the issue. 

Cheers

**Comment by bfocht** [comment]
Thanks for the feedback.  For the login and cart to work correctly, you must have a _custom domain_ configured that matches your site url.  For example if your WordPress site is www.example.com then your _custom domain_ should be configured to something like store.example.com.

Please contact our customer support and they can help you with setting up your _custom domain_ in the Reseller Control Center.  You can find our support contact information on the dashboard in the Reseller Control Center.
