### ISSUE TITLE
Chrome v66 does not add items to cart

### ISSUE THREAD

**Issue by dereckmartin** [godaddy/wp-reseller-store#65]
When using Google Chrome v66 on a Mac, any item added does not properly show in the cart.  The API request sent to update the cart returns 200, and cart counter is updated.  However, the cart appears empty when viewed.  This scenario does not happen on Firefox or Google Chrome v66 on Android.

**Comment by bfocht** [comment]
We have just published an updated version of the plugin with fixes for browsers that have stricter privacy settings.  This version is v2.1.1  Here is an overview of the plugin updates.  https://youtu.be/eadC9vGwPxE
