### ISSUE TITLE
Product Pod modification.

### ISSUE THREAD

**Issue by brown7477** [godaddy/wp-reseller-store#68]
Display plan options in the product pods.
Display options for customer to select length of plan before adding to cart.
Also add option to add upsell items to the product pods.

**Comment by bfocht** [comment]
@brown7477 We have added a configure page flow to the storefront and plugin that provides the shopper with the options to select different terms and also offers up/cross sell items such as SSL, backup, and security.  Here is an overview of the changes in v2.1.1 plugin updates https://youtu.be/eadC9vGwPxE
