### ISSUE TITLE
Advanced Domain Search Widget not working correctly on Elementor

### ISSUE THREAD

**Issue by mattssn** [godaddy/wp-reseller-store#69]
Heya, I am setting up  reseller site with elementor, and so far so good except the advanced domain search does not seem to work properly with this builder, the formatting seems all incorrect, I will post screenshots below. 

https://i.imgur.com/yLIMprW.png

https://i.imgur.com/rLweNvf.png

When you search a domain it does not show the add to cart button or and text on the search button, I could probably fix the formatting to make it go full width, but this does not fix the appearance of the buttons

**Comment by bfocht** [comment]
We have published an updated version of the domain search widget with version 2.1.1 update.  This includes some new CSS as well as the ability to display the search results in a modal window.  Here is an overview of the updated plugin https://youtu.be/eadC9vGwPxE
