### ISSUE TITLE
Sign in Widget

### ISSUE THREAD

**Issue by cre8mysite** [godaddy/wp-reseller-store#73]
Good day! I have cre8ed a pretty amazing site with the Reseller Store Plugin, and Elementor. 
I want the sign in to display the Users Name next to "welcome back" once they have logged in. Is this possible?

**Comment by cre8mysite** [comment]
I have the Custom domain set to use my word-press site, and also a Sub-domain set to display my Turnkey Storefront designed by go-daddy. All I am needing is the Users Name to display next to "Welcome Back" once they have logged in and start shopping on my WordPress site. Is there something I can add to the short-code 
[rstore_login welcome_message=”Welcome Back” login_button_text=”Log In” logout_button_text=”Log Out” ]
That will display their name?

**Comment by theblackdie** [comment]
the reseller shopper login is messed up totally
it displays at the same time:
Welcome back, sign in, logout !!!!!
it must be either sign in either logout 
come one guys it was working well before this update (2.0.7)

**Comment by hostbrook** [comment]
> the reseller shopper login is messed up totally
> it displays at the same time:
> Welcome back, sign in, logout !!!!!
> it must be either sign in either logout
> come one guys it was working well before this update (2.0.7)

Hi theblackdie! Have you solved the issue? I have the same....
I don't know where to digg...

**Comment by hostbrook** [comment]
@theblackdie 
Issue fixed. All that you need is just update storefront to version 2.0.10.

**Comment by theblackdie** [comment]
where can I find it?

**Comment by hostbrook** [comment]
> where can I find it?
please watch this video:
[https://www.youtube.com/watch?v=5K1GXDGVwyg](https://www.youtube.com/watch?v=5K1GXDGVwyg)
also, if you are a reseller, join the community [Wild West Reseller Stampede](https://plus.google.com/communities/110833808277616099110/) - here is a lot of useful info.

**Comment by bfocht** [comment]
@cre8mysite We have published a v2.1.1 to the WordPress directory which supports compatibility fixes with WordPress 5.0.1 and later as well as safari fixes.  If you are still having an issue, please contact our support team and they can open a ticket for our developers to research further.
